-- Crear la base de datos
CREATE DATABASE IF NOT EXISTS EMPLEADOS;
USE EMPLEADOS;

-- Crear la tabla DEPARTAMENTO Esta tabla la he creado para aumentar un poco la complejidad del ejercicio, y asi usar joins o subconsultas (lo puedes ver en mostrar todo aunque es muy simple).
CREATE TABLE DEPARTAMENTO (
    DEPARTAMENTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DEPARTAMENTO VARCHAR(100) NOT NULL
);

-- Crear la tabla EMPLEADO
CREATE TABLE EMPLEADO (
    EMPLEADO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_EMPLEADO VARCHAR(100) NOT NULL,
    APELLIDO_EMPLEADO VARCHAR(100) NOT NULL,
    PUESTO VARCHAR(100) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    DEPARTAMENTO_ID INT NOT NULL,
    FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO(DEPARTAMENTO_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);
